title          : "BrainIAK: Running Searchlight"
description    : >
  This project is an introduction to running searchlights on BrainIAK. 
language       : python
from           : 'python-notebooks-prod:93'
runtime_config : default
state          : development
long_description: |
  In this project, you will get a gentle introduction to DataCamp Projects. We will
  walk you through the projects interface interactively. You will learn how
  to work with jupyter notebooks, complete tasks, check your work, and successfully
  finish your project!
technology: 2
instructors:
  - michael@datacamp.com
collaborators:
topics:
  - 8
time_needed: "90 minutes"
illustration: "https://assets.datacamp.com/production/project_10/datasets/shield_image.png"
